---
title: "R Notebook"
output: word_document
---


6.25Compute the 95% confidence interval forμwhen X ~ N(140,25ˆ2)
```{r}
ci_mean <- function(xbar, s, n){
  error <- qt(.975, n-1)*s/sqrt(n)
  upper <- xbar + error
  lower <- xbar -error
  rbind(c("lower","upper"),c(lower, upper))
}
ci_mean(140,25,200)

```

.27Compute the point estimate for the probability of failure
```{r}
phat <- 6/46
```


6.28Compute the 95% confidence interval for p.
```{r}

# In R the easiest way to get CI for proportion in using prop.test()# function. The CI and p is given at the end of the output as you can see here.
prop.test(6, 46, p = NULL, alternative =c("two.sided"), conf.level = 0.95, correct = TRUE)
```



6.31Compute the 99% CI for ??ˆ2
```{r}
var.ci =function(n, var, conf.level = 0.99){
  # Get chi-sq estimates using qchisq() function. It's works just like qnorm()
  chilower =qchisq((1-conf.level)/2, n-1)
  chiupper =qchisq((1-conf.level)/2, n-1, lower.tail =FALSE)
  c((n-1)*var/chiupper, (n-1)*var/chilower)}
var.ci(25, 4)
```

6.32The length of a 95% confidence interval forμfrom a sample is.
```{r}

s <- 2
n <- (2*qnorm(0.975)*s/0.5)^2
# assuming large n we can use z distribution here instead of t.
n
```

6.64Compute the 95% confidence interval forμand ??ˆ2

```{r}
# First input the data
time <-c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
count <-c(2, 6, 9, 33, 49, 66, 52, 37, 18, 11, 4)
# Make a data frame
df <-data.frame(time, count)
library(psych)# Need Hmisc package for weighted stats. Base R only has weighted mean function.
library(Hmisc)

```

```{r}
x_bar <- wtd.mean(time,count)
var <- wtd.var(time,count)
ci_mean(x_bar, sqrt(var), 287)
```

```{r}
var.ci(287, var, conf.level = 0.95)

```








